// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdWq9P714dDTJTKEAtt2351CmhFjjJGt4',
    appId: '1:491051517020:web:6a0a79128c6620bc3a5299',
    messagingSenderId: '491051517020',
    projectId: 'demoapp-2cd47',
    authDomain: 'demoapp-2cd47.firebaseapp.com',
    storageBucket: 'demoapp-2cd47.firebasestorage.app',
    measurementId: 'G-NJWP4XMBTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUPbLGA8G8e17jvcMmLqf5RWyGudgP4BU',
    appId: '1:491051517020:android:a8d69d6bf64badd33a5299',
    messagingSenderId: '491051517020',
    projectId: 'demoapp-2cd47',
    storageBucket: 'demoapp-2cd47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl7msiI_8dycKr3GwZ7zH8A-mrsDY5tvY',
    appId: '1:491051517020:ios:1283b6fcffdf06813a5299',
    messagingSenderId: '491051517020',
    projectId: 'demoapp-2cd47',
    storageBucket: 'demoapp-2cd47.firebasestorage.app',
    iosBundleId: 'com.example.flutterDeepLearningDemo',
  );
}
